force-app/main/default/objects/Funnel_Addition_Target__c/Funnel_Addition_Target__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition Target</label>
    <nameField>
        <displayFormat>FAT-{0000000}</displayFormat>
        <label>Funnel Addition Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Addition Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Amount_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Amount_at_Start__c</fullName>
    <label>Amount at Start of Period</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <label>Current Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Quote_Config__c.field-meta.xml
<CustomField>
    <fullName>Quote_Config__c</fullName>
    <label>Annual Quota Config</label>
    <referenceTo>Annual_Quota_Config__c</referenceTo>
    <relationshipLabel>Funnel Addition Targets</relationshipLabel>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Rep__c.field-meta.xml
<CustomField>
    <fullName>Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fiscal_Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <masterLabel>Fiscal Year</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>P4</fullName>
    </customValue>
    <customValue>
        <fullName>P5</fullName>
    </customValue>
    <customValue>
        <fullName>P6</fullName>
    </customValue>
    <customValue>
        <fullName>P7</fullName>
    </customValue>
    <customValue>
        <fullName>P8</fullName>
    </customValue>
    <customValue>
        <fullName>P9</fullName>
    </customValue>
    <customValue>
        <fullName>P10</fullName>
    </customValue>
    <customValue>
        <fullName>P11</fullName>
    </customValue>
    <customValue>
        <fullName>P12</fullName>
    </customValue>
    <masterLabel>Period</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Selectors/FunnelAdditionTargetSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class FunnelAdditionTargetSelector extends SObjectSelector{

    public FunnelAdditionTargetSelector(){
        super(Funnel_Addition_Target__c.SObjectType);
    }

    private static FunnelAdditionTargetSelector m_instance;
    public static FunnelAdditionTargetSelector Instance {
        get {
            if(m_instance != null) { return m_instance; }
            System.debug('##New Funnel Addition Target Selector Instance Create');
            m_instance = new FunnelAdditionTargetSelector();
            return m_instance;
        }
    }


    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField>{
                Funnel_Addition_Target__c.Id,
                Funnel_Addition_Target__c.Name,
                Funnel_Addition_Target__c.Period__c ,
                Funnel_Addition_Target__c.Fiscal_Year__c,
                Funnel_Addition_Target__c.Territory__c,
                Funnel_Addition_Target__c.Amount_at_Start__c,
                Funnel_Addition_Target__c.Current_Amount__c,
                Funnel_Addition_Target__c.Quote_Config__c,
                Funnel_Addition_Target__c.Rep__c
        };
    }

    public List<Funnel_Addition_Target__c> GetById(Set<Id> keyset) {
        return queryById(keyset);
    }

    public List<Funnel_Addition_Target__c> GetBYName(String name) {
        return queryByName(name);
    }

    public List<Funnel_Addition_Target__c> GetAll() {
        return queryAll();
    }

    public List<Funnel_Addition_Target__c> GetByPeriod(String key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Funnel_Addition_Target__c.Period__c, key)).Execute();
    }

    public List<Funnel_Addition_Target__c> GetByQuotaConfig(Id key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Funnel_Addition_Target__c.Quote_Config__c, key))
                .Execute();
    }
}