force-app/main/default/objects/Funnel_Addition_Target__c/Funnel_Addition_Target__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition Target</label>
    <nameField>
        <displayFormat>FAT-{0000000}</displayFormat>
        <label>Funnel Addition Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Addition Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Rep__c.field-meta.xml
<CustomField>
    <fullName>Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fiscal_Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <masterLabel>Fiscal Year</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>P4</fullName>
    </customValue>
    <customValue>
        <fullName>P5</fullName>
    </customValue>
    <customValue>
        <fullName>P6</fullName>
    </customValue>
    <customValue>
        <fullName>P7</fullName>
    </customValue>
    <customValue>
        <fullName>P8</fullName>
    </customValue>
    <customValue>
        <fullName>P9</fullName>
    </customValue>
    <customValue>
        <fullName>P10</fullName>
    </customValue>
    <customValue>
        <fullName>P11</fullName>
    </customValue>
    <customValue>
        <fullName>P12</fullName>
    </customValue>
    <masterLabel>Period</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Trigger Handlers/FunnelAdditionTargetTriggerHandler.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class FunnelAdditionTargetTriggerHandler {
    public static void Execute() {
        if(Trigger.isExecuting) {
            if (Trigger.isBefore) {
                if (Trigger.isInsert) {
                    beforeInsertActions();
                }

            }
        }
    }

    public static void beforeInsertActions(){
        List<Funnel_Addition_Target__c> targets = FunnelAdditionTargetSelector.Instance.GetAll();
        for(Funnel_Addition_Target__c target : (List<Funnel_Addition_Target__c>) Trigger.new) {
            DuplicateHandler(target, targets);
        }
    }

    private static void DuplicateHandler(Funnel_Addition_Target__c mTarget,
            List<Funnel_Addition_Target__c> targets) {
        Boolean value = false;
        //AnnualTargetSelector selector = new AnnualTargetSelector();

        for(Funnel_Addition_Target__c trg : targets) {
            if(trg.Fiscal_Year__c == mTarget.Fiscal_Year__c) {
                if(trg.Period__c == mTarget.Period__c) {
                    if(trg.Territory__c == mTarget.Territory__c) {
                        if(trg.Rep__c == mTarget.Rep__c) {
                            cq.App.Logger.Warning('[FunnelAdditionTarget Error] ===> Duplicate FunnelAdditionTarget ' +
                                    'Found');
                            throw new TargetException('[FunnelAdditionTarget Error] ===> Duplicate FunnelAdditionTarget Found');
                        }
                    }
                }
            }
        }

    }

    private virtual class FunnelAdditionTargetException extends Exception { }
    private class TargetException extends FunnelAdditionTargetException {
        String message;
    }
}