force-app/main/default/objects/Funnel_Addition__c/Funnel_Addition__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>Funnel Addition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Additions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition__c/fields/Amount_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Amount_at_Start__c</fullName>
    <label>Amount at Start</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Close_Date_at_End__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_at_End__c</fullName>
    <label>Close Date at End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Close_Date_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_at_Start__c</fullName>
    <label>Close Date at Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <label>Current Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Current_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Period__c</fullName>
    <label>Current Period</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Funnel_Addition_Target__c.field-meta.xml
<CustomField>
    <fullName>Funnel_Addition_Target__c</fullName>
    <label>Funnel Addition Target</label>
    <referenceTo>Funnel_Addition_Target__c</referenceTo>
    <relationshipLabel>Funnel Additions</relationshipLabel>
    <relationshipName>Funnel_Additions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Funnel Additions</relationshipLabel>
    <relationshipName>Funnel_Additions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Probability_At_Start__c.field-meta.xml
<CustomField>
    <fullName>Probability_At_Start__c</fullName>
    <label>Probability At Start</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/Funnel_Addition_Target__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition Target</label>
    <nameField>
        <displayFormat>FAT-{0000000}</displayFormat>
        <label>Funnel Addition Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Addition Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Amount_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Amount_at_Start__c</fullName>
    <label>Amount at Start of Period</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <label>Current Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Rep__c.field-meta.xml
<CustomField>
    <fullName>Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>P4</fullName>
    </customValue>
    <customValue>
        <fullName>P5</fullName>
    </customValue>
    <customValue>
        <fullName>P6</fullName>
    </customValue>
    <customValue>
        <fullName>P7</fullName>
    </customValue>
    <customValue>
        <fullName>P8</fullName>
    </customValue>
    <customValue>
        <fullName>P9</fullName>
    </customValue>
    <customValue>
        <fullName>P10</fullName>
    </customValue>
    <customValue>
        <fullName>P11</fullName>
    </customValue>
    <customValue>
        <fullName>P12</fullName>
    </customValue>
    <masterLabel>Period</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Services/FunnelAdditionService.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class FunnelAdditionService {

    private static FunnelAdditionService m_actions;
    public static FunnelAdditionService Action {
        get {
            if(m_actions != null) { return m_actions;}
            m_actions = new FunnelAdditionService();
            return m_actions;
        }
    }

    public Map<String, Object> FunnelAdditionByOpportunity(List<Opportunity> opps) {
        Map<String, Object> data = new Map<String, Object>();
        //Map<Id, Opportunity> oMap = new Map<Id, Opportunity>(opps);
        Set<Id> keyset = new Set<Id>();
        for(Opportunity op : opps) {
            keyset.add(op.Id);
        }

        List<Funnel_Addition__c> additions = [SELECT Id, Opportunity__c, Amount_at_Start__c, Current_Amount__c,
                Current_Period__c, Close_Date_at_Start__c, Close_Date_at_End__c, Period__c, Funnel_Addition_Target__c
        FROM Funnel_Addition__c
        WHERE Opportunity__c IN: keyset];
        data.put('current', additions);

        return data;
    }

    public List<Funnel_Addition__c> CreateNewAdditionsForNewOpps(List<Opportunity> opportunities) {
        List<Funnel_Addition__c> newAddition = new List<Funnel_Addition__c>();
        Set<Id> repId = new Set<Id>();
        for(Opportunity op : opportunities) { repId.add(op.OwnerId);}
        Map<Id, Funnel_Addition_Target__c> targetMap = new Map<Id, Funnel_Addition_Target__c>();
        targetMap.putAll( (List<Funnel_Addition_Target__c>) FunnelAdditionTargetSelector.Instance.GetQueryFactory().WithCriteria(Criteria.ValueIn(Funnel_Addition_Target__c.Rep__c, repId)).Execute());

        Map<Id, Period> periodMap = new Map<Id, Period>(DefaultPeriodSelector.Instance.GetByFiscalYear(String.valueOf(Date.today().year())));
        for(Opportunity o : opportunities) {
            for(Id key : targetMap.keySet()) {
                Funnel_Addition_Target__c trgt = targetMap.get(key);
                if(trgt.Rep__c == o.OwnerId) {
                    String prd = '';
                    for(Id k : periodMap.keySet()) {
                        Period p = periodMap.get(k);
                        if(p.StartDate <= o.CloseDate && p.EndDate >= o.CloseDate) {
                            prd = 'P' + p.Number;
                        }
                    }
                    newAddition.add(new Funnel_Addition__c(
                            Amount_at_Start__c  = o.Amount,
                            Close_Date_at_Start__c = o.CloseDate,
                            Probability_At_Start__c = o.Probability,
                            Opportunity__c = o.Id,
                            Funnel_Addition_Target__c =trgt.Id,
                            Period__c = prd
                    ));
                }
            }
        }

        return newAddition;
    }

}