force-app/main/default/objects/Funnel_Addition__c/Funnel_Addition__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>Funnel Addition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Additions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition__c/fields/Amount_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Amount_at_Start__c</fullName>
    <label>Amount at Start</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Close_Date_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_at_Start__c</fullName>
    <label>Close Date at Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Probability_At_Start__c.field-meta.xml
<CustomField>
    <fullName>Probability_At_Start__c</fullName>
    <label>Probability At Start</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/Utils/AnnualTargetUtils.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class AnnualTargetUtils {

    public Funnel_Addition__c CreateNewFunnelAddition(Opportunity opportunity) {
        Funnel_Addition__c iAddition = new Funnel_Addition__c();
        iAddition.Amount_at_Start__c = opportunity.Amount;
        iAddition.Close_Date_at_Start__c = opportunity.CloseDate;
        iAddition.Probability_At_Start__c = opportunity.Probability;

        return iAddition;
    }

    public Boolean IsThereExistingFunnelAddition(Opportunity opportunity) {
        FunnelAdditionSelector selector = new FunnelAdditionSelector();
        Boolean val = true;

        if(selector.GetByOpportunity(opportunity.Id).isEmpty()) {
            val = false;
        }

        return val;
    }

    public Boolean IsMovedOutOfCurrentPeriod(Funnel_Addition__c addition, Opportunity opportunity, Boolean
            CustomPeriodOverride) {
        Boolean value = false;
        if(CustomPeriodOverride == false) {
            DefaultPeriodSelector selector = new DefaultPeriodSelector();
            //List<Period> periods = selector.GetWhereDateIn()
        }
        return value;

    }
}