force-app/main/default/objects/Funnel_Addition__c/Funnel_Addition__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition</label>
    <nameField>
        <displayFormat>FA-{0000000}</displayFormat>
        <label>Funnel Addition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Additions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition__c/fields/Amount_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Amount_at_Start__c</fullName>
    <label>Amount at Start</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Close_Date_at_End__c.field-meta.xml
<CustomField>
    <fullName>Close_Date_at_End__c</fullName>
    <label>Close Date at End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <label>Current Amount</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Current_Amount_FF__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount_FF__c</fullName>
    <formula>Opportunity__r.Amount</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Amount FF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Current_Period__c.field-meta.xml
<CustomField>
    <fullName>Current_Period__c</fullName>
    <label>Current Period</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Funnel_Addition_Target__c.field-meta.xml
<CustomField>
    <fullName>Funnel_Addition_Target__c</fullName>
    <label>Funnel Addition Target</label>
    <referenceTo>Funnel_Addition_Target__c</referenceTo>
    <relationshipLabel>Funnel Additions</relationshipLabel>
    <relationshipName>Funnel_Additions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Funnel Additions</relationshipLabel>
    <relationshipName>Funnel_Additions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/Funnel_Addition_Target__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition Target</label>
    <nameField>
        <displayFormat>FAT-{0000000}</displayFormat>
        <label>Funnel Addition Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Addition Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Amount_at_Start__c.field-meta.xml
<CustomField>
    <fullName>Amount_at_Start__c</fullName>
    <label>Amount at Start of Period</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Current_Amount__c.field-meta.xml
<CustomField>
    <fullName>Current_Amount__c</fullName>
    <label>Current Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>P4</fullName>
    </customValue>
    <customValue>
        <fullName>P5</fullName>
    </customValue>
    <customValue>
        <fullName>P6</fullName>
    </customValue>
    <customValue>
        <fullName>P7</fullName>
    </customValue>
    <customValue>
        <fullName>P8</fullName>
    </customValue>
    <customValue>
        <fullName>P9</fullName>
    </customValue>
    <customValue>
        <fullName>P10</fullName>
    </customValue>
    <customValue>
        <fullName>P11</fullName>
    </customValue>
    <customValue>
        <fullName>P12</fullName>
    </customValue>
    <masterLabel>Period</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Selectors/FunnelAdditionSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class FunnelAdditionSelector extends SObjectSelector {

    public FunnelAdditionSelector() {
        super(Funnel_Addition__c.SObjectType);
    }

    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField>{
                Funnel_Addition__c.Id,
                Funnel_Addition__c.Name,
                Funnel_Addition__c.Amount_at_Start__c,
                Funnel_Addition__c.Current_Amount__c,
                Funnel_Addition__c.Current_Period__c,
                Funnel_Addition__c.Current_Amount_FF__c,
                Funnel_Addition__c.Close_Date_at_End__c,
                Funnel_Addition__c.Close_Date_at_End__c,
                Funnel_Addition__c.Period__c,
                Funnel_Addition__c.Funnel_Addition_Target__c,
                Funnel_Addition__c.Opportunity__c
        };
    }

    public List<Funnel_Addition__c> GetById(Set<Id> idset) {
        List<Funnel_Addition__c> targets = queryById(idset);
        return targets;
    }

    public List<Funnel_Addition__c> GetByName(String name) {
        List<Funnel_Addition__c> targets = queryByName(name);
        return targets;
    }

    public List<Funnel_Addition__c> GetByOpportunity(Id key) {
        List<Funnel_Addition__c> targets = GetQueryFactory().WithCriteria(Criteria.Equals(Funnel_Addition__c.Opportunity__c, key)).Execute();
        return targets;
    }

    public List<Funnel_Addition__c> GeyByOpportunity(Set<Id> keyset) {
        List<Funnel_Addition__c> targets = GetQueryFactory().WithCriteria(Criteria.ValueIn(Funnel_Addition__c.Opportunity__c, keyset)).Execute();
        return targets;
    }

    public List<Funnel_Addition__c> GetAll() {
        return queryAll();
    }
}