force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/Annual_Funnel_Addition_Target_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Funnel Addition Target Config</label>
    <nameField>
        <displayFormat>FATC-{00000}</displayFormat>
        <label>Annual Funnel Addition Target Config Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Funnel Addition Target Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/Annual_Config_Name__c.field-meta.xml
<CustomField>
    <fullName>Annual_Config_Name__c</fullName>
    <formula>HYPERLINK(
     &quot;/&quot; &amp; Id,
     Label__c  , 
     &quot;_self&quot;
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Annual Config Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/UseCustomPeriod__c.field-meta.xml
<CustomField>
    <fullName>UseCustomPeriod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Period Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Selectors/AnnualTargetSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class AnnualTargetSelector extends SObjectSelector {

    public AnnualTargetSelector() {
        super(Annual_Funnel_Addition_Target_Config__c.SObjectType);
    }


    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField>{
                Annual_Funnel_Addition_Target_Config__c.Id,
                Annual_Funnel_Addition_Target_Config__c.Name,
                Annual_Funnel_Addition_Target_Config__c.IsActive__c ,
                Annual_Funnel_Addition_Target_Config__c.Fiscal_Year__c,
                Annual_Funnel_Addition_Target_Config__c.Label__c,
                Annual_Funnel_Addition_Target_Config__c.Territory__c,
                Annual_Funnel_Addition_Target_Config__c.Annual_Config_Name__c,
                Annual_Funnel_Addition_Target_Config__c.UseCustomPeriod__c,
                Annual_Funnel_Addition_Target_Config__c.Target__c
        };
    }

    public List<Annual_Funnel_Addition_Target_Config__c> GetAll() {
        return queryAll();
    }

    public List<Annual_Funnel_Addition_Target_Config__c> GetById(Set<Id> keyset) {
        return queryById(keyset);
    }

    public List<Annual_Funnel_Addition_Target_Config__c> GetActive() {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Funnel_Addition_Target_Config__c.IsActive__c, true)).Execute();
    }

    public  List<Annual_Funnel_Addition_Target_Config__c> GetByFiscalYear(String key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Funnel_Addition_Target_Config__c.Fiscal_Year__c, key)).Execute();
    }
}