force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/Annual_Funnel_Addition_Target_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Funnel Addition Target Config</label>
    <nameField>
        <displayFormat>FATC-{00000}</displayFormat>
        <label>Annual Funnel Addition Target Config Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Funnel Addition Target Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/Target__c.field-meta.xml
<CustomField>
    <fullName>Target__c</fullName>
    <label>Target</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/Annual_Quota_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Quota Config</label>
    <nameField>
        <displayFormat>AQC-{000000}</displayFormat>
        <label>Annual Quota Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Quota Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Quota_Config__c/fields/Annual_Funnel_Addition_Target_Config__c.field-meta.xml
<CustomField>
    <fullName>Annual_Funnel_Addition_Target_Config__c</fullName>
    <label>Annual Funnel Addition Target Config</label>
    <referenceTo>Annual_Funnel_Addition_Target_Config__c</referenceTo>
    <relationshipLabel>Annual Quota Configs</relationshipLabel>
    <relationshipName>Annual_Quota_Configs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/AnnualTarget__c.field-meta.xml
<CustomField>
    <fullName>AnnualTarget__c</fullName>
    <label>Target(Annualized)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/Period_Target__c.field-meta.xml
<CustomField>
    <fullName>Period_Target__c</fullName>
    <label>Target(By Period)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Trigger Handlers/AnnualQuotaConfigTriggerHandler.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class AnnualQuotaConfigTriggerHandler {

    public static void Execute() {
        if(Trigger.isExecuting) {
            if(Trigger.isBefore){
                if(Trigger.isInsert) {
                    beforeInsertActions();
                }else if(Trigger.isUpdate) {
                    beforeUpdateActions();
                }else if(Trigger.isDelete) {

                }
            }
        }
    }

    private static void beforeInsertActions() {

        List<Annual_Quota_Config__c> quotaConfigs = Trigger.new;
        AnnualTargetSelector iSelector = new AnnualTargetSelector();
        for(Annual_Quota_Config__c mConfig : quotaConfigs) {
            Annual_Funnel_Addition_Target_Config__c pConfig = iSelector.GetById(new Set<Id>{ mConfig
                    .Annual_Funnel_Addition_Target_Config__c})[0];
            mConfig.AnnualTarget__c = pConfig.Target__c;
            mConfig.Period_Target__c = pConfig.Target__c/12;
        }
    }

    private static void beforeUpdateActions() {
        List<Annual_Quota_Config__c> quotaConfigs = Trigger.new;
        AnnualTargetSelector iSelector = new AnnualTargetSelector();
        for(Annual_Quota_Config__c mConfig : quotaConfigs) {
            Annual_Funnel_Addition_Target_Config__c pConfig = iSelector.GetById(new Set<Id>{ mConfig
                    .Annual_Funnel_Addition_Target_Config__c})[0];
            mConfig.AnnualTarget__c = pConfig.Target__c;
            mConfig.Period_Target__c = pConfig.Target__c/12;
        }
    }

}