force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/Annual_Funnel_Addition_Target_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Funnel Addition Target Config</label>
    <nameField>
        <displayFormat>FATC-{00000}</displayFormat>
        <label>Annual Funnel Addition Target Config Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Funnel Addition Target Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Period_Config__c/Period_Config__c.object-meta.xml
<CustomObject>
    <label>Period Config</label>
    <nameField>
        <displayFormat>PC-{000000}</displayFormat>
        <label>Period Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Period Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Period_Config__c/fields/Annual_Funnel_Addition_Target_Config__c.field-meta.xml
<CustomField>
    <fullName>Annual_Funnel_Addition_Target_Config__c</fullName>
    <label>Annual Funnel Addition Target Config</label>
    <referenceTo>Annual_Funnel_Addition_Target_Config__c</referenceTo>
    <relationshipLabel>Period Configs</relationshipLabel>
    <relationshipName>Period_Configs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Selectors/CustomPeriodSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class CustomPeriodSelector extends SObjectSelector {

    public CustomPeriodSelector() {
        super(Period_Config__c.SObjectType);
    }

    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField>{
                Period_Config__c.Id,
                Period_Config__c.Name,
                Period_Config__c.Annual_Funnel_Addition_Target_Config__c,
                Period_Config__c.IsDeleted
        };
    }

    public List<Period_Config__c> GetAll() {
        return queryAll();
    }

    public List<Period_Config__c> GetById(Set<Id> keyset) {
        return queryById(keyset);
    }

    public List<Period_Config__c> GetById(Id key) {
        Set<Id> keyset = new Set<Id>();
        keyset.add(key);
        return queryById(keyset);
    }

    public List<Period_Config__c> GeyByName(String name) {
        return queryByName(name);
    }

    public List<Period_Config__c> GetByAnnualConfigs(Id key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Period_Config__c.Annual_Funnel_Addition_Target_Config__c, key)).Execute();
    }

}