force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/Annual_Funnel_Addition_Target_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Funnel Addition Target Config</label>
    <nameField>
        <displayFormat>FATC-{00000}</displayFormat>
        <label>Annual Funnel Addition Target Config Nam</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Funnel Addition Target Configs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/Territory__c.field-meta.xml
<CustomField>
    <fullName>Territory__c</fullName>
    <label>Territory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Territory</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Annual_Funnel_Addition_Target_Config__c/fields/UseCustomPeriod__c.field-meta.xml
<CustomField>
    <fullName>UseCustomPeriod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom Period Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/Annual_Quota_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Quota Config</label>
    <nameField>
        <displayFormat>AQC-{000000}</displayFormat>
        <label>Annual Quota Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Quota Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Quota_Config__c/fields/Annual_Funnel_Addition_Target_Config__c.field-meta.xml
<CustomField>
    <fullName>Annual_Funnel_Addition_Target_Config__c</fullName>
    <label>Annual Funnel Addition Target Config</label>
    <referenceTo>Annual_Funnel_Addition_Target_Config__c</referenceTo>
    <relationshipLabel>Annual Quota Configs</relationshipLabel>
    <relationshipName>Annual_Quota_Configs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/AnnualTarget__c.field-meta.xml
<CustomField>
    <fullName>AnnualTarget__c</fullName>
    <label>Target(Annualized)</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/IsSeller__c.field-meta.xml
<CustomField>
    <fullName>IsSeller__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSeller</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/Period_Target__c.field-meta.xml
<CustomField>
    <fullName>Period_Target__c</fullName>
    <label>Target(By Period)</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/Rep__c.field-meta.xml
<CustomField>
    <fullName>Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Annual_Quota_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Annual_Quota_Config__c/fields/UseCustomPeriod__c.field-meta.xml
<CustomField>
    <fullName>UseCustomPeriod__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Use Custom Period</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Selectors/AnnualQuotaSelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class AnnualQuotaSelector extends SObjectSelector {
    public AnnualQuotaSelector() {
        super(Annual_Quota_Config__c.SObjectType);
    }

    private static AnnualQuotaSelector m_instance;
    public static AnnualQuotaSelector Instance{
        get {
            if(m_instance != null){ return m_instance;}
            m_instance = new AnnualQuotaSelector();
            return m_instance;
        }
    }


    public override Set<SObjectField> GetDefaultFields() {
        return new Set<SObjectField> {
                Annual_Quota_Config__c.Id,
                Annual_Quota_Config__c.Name,
                Annual_Quota_Config__c.IsSeller__c,
                Annual_Quota_Config__c.AnnualTarget__c,
                Annual_Quota_Config__c.Period_Target__c,
                Annual_Quota_Config__c.Rep__c,
                Annual_Quota_Config__c.CreatedById,
                Annual_Quota_Config__c.CreatedDate,
                Annual_Quota_Config__c.LastModifiedById,
                Annual_Quota_Config__c.LastModifiedDate ,
                Annual_Quota_Config__c.Fiscal_Year__c,
                Annual_Quota_Config__c.Territory__c,
                Annual_Quota_Config__c.UseCustomPeriod__c,
                Annual_Quota_Config__c.Name__c
        };
    }

    public List<Annual_Quota_Config__c> GetById(Set<id> idset) {
        return queryById(idset);
    }

    public List<Annual_Quota_Config__c> GetByName(String name) {
        return queryByName(name);
    }

    public List<Annual_Quota_Config__c> GetAll() {
        return queryAll();
    }

    public List<Annual_Quota_Config__c> GetSellerConfig() {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Quota_Config__c.IsSeller__c, true)).Execute();
    }

    public List<Annual_Quota_Config__c> GetBySeller(Set<Id> idset) {
        return GetQueryFactory().WithCriteria(Criteria.ValueIn(Annual_Quota_Config__c.Rep__c, idset)).Execute();
    }

    public List<Annual_Quota_Config__c> GetOneBySeller(Id key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Quota_Config__c.Rep__c, key)).Execute();
    }

    public List<Annual_Quota_Config__c> GetByTargetConfig(Id key){
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Quota_Config__c.Annual_Funnel_Addition_Target_Config__c, key)).Execute();
    }

    public List<Annual_Quota_Config__c> GetByLabel(String key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Quota_Config__c.Name__c, key)).Execute();
    }

    public List<Annual_Quota_Config__c> GetByFiscalYear(String key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Annual_Quota_Config__c.Fiscal_Year__c, key)).Execute();
    }
}