force-app/main/default/objects/Annual_Quota_Config__c/Annual_Quota_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Quota Config</label>
    <nameField>
        <displayFormat>AQC-{000000}</displayFormat>
        <label>Annual Quota Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Quota Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Quota_Config__c/fields/IsSeller__c.field-meta.xml
<CustomField>
    <fullName>IsSeller__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsSeller</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/Funnel_Addition_Target__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition Target</label>
    <nameField>
        <displayFormat>FAT-{0000000}</displayFormat>
        <label>Funnel Addition Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Addition Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Quote_Config__c.field-meta.xml
<CustomField>
    <fullName>Quote_Config__c</fullName>
    <label>Annual Quota Config</label>
    <referenceTo>Annual_Quota_Config__c</referenceTo>
    <relationshipLabel>Funnel Addition Targets</relationshipLabel>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Services/AnnualQuotaService.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class AnnualQuotaService {
    private static AnnualQuotaService m_actions;
    public static AnnualQuotaService Action {
        get {
            if(m_actions != null) { return m_actions;}
            m_actions = new AnnualQuotaService();
            return m_actions;
        }
    }


    public void afterInsertHandler(Map<Id, Annual_Quota_Config__c> records) {
        Map<Id, Funnel_Addition_Target__c> targetList = new Map<Id, Funnel_Addition_Target__c>([SELECT Id, Quote_Config__c FROM Funnel_Addition_Target__c WHERE
                Quote_Config__c =: records.keySet()]);

        if(targetList.isEmpty()) {
            List<Funnel_Addition_Target__c> targetsToInsert = new List<Funnel_Addition_Target__c>();
            for(Id key : records.keySet()) {
                Annual_Quota_Config__c c = records.get(key);
                if(c.IsSeller__c) {
                    if(AnnualTargetUtils.Utils.HasAccessToNewFeature(UserInfo.getUserId())) {
                        targetsToInsert.addAll(FunnelAdditionTargetService.Action.GenerateNewTargetForQuotaConfiguration(c));
                    }
                }
            }
            insert targetsToInsert;
        }else if(targetList.size() > 1) {

        }else {
            System.debug('Doing Nothing');
        }
    }

}