force-app/main/default/objects/Annual_Quota_Config__c/Annual_Quota_Config__c.object-meta.xml
<CustomObject>
    <label>Annual Quota Config</label>
    <nameField>
        <displayFormat>AQC-{000000}</displayFormat>
        <label>Annual Quota Config Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Quota Configs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Quota_Config__c/fields/Rep__c.field-meta.xml
<CustomField>
    <fullName>Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Annual_Quota_Configs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/Funnel_Addition_Target__c.object-meta.xml
<CustomObject>
    <label>Funnel Addition Target</label>
    <nameField>
        <displayFormat>FAT-{0000000}</displayFormat>
        <label>Funnel Addition Target Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funnel Addition Targets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fiscal_Year</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <label>Period</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Period</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Quote_Config__c.field-meta.xml
<CustomField>
    <fullName>Quote_Config__c</fullName>
    <label>Annual Quota Config</label>
    <referenceTo>Annual_Quota_Config__c</referenceTo>
    <relationshipLabel>Funnel Addition Targets</relationshipLabel>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Funnel_Addition_Target__c/fields/Rep__c.field-meta.xml
<CustomField>
    <fullName>Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Funnel_Addition_Targets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Fiscal_Year.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>2022</fullName>
    </customValue>
    <customValue>
        <fullName>2023</fullName>
    </customValue>
    <customValue>
        <fullName>2024</fullName>
    </customValue>
    <customValue>
        <fullName>2025</fullName>
    </customValue>
    <customValue>
        <fullName>2026</fullName>
    </customValue>
    <customValue>
        <fullName>2027</fullName>
    </customValue>
    <customValue>
        <fullName>2028</fullName>
    </customValue>
    <masterLabel>Fiscal Year</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Period.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>P1</fullName>
    </customValue>
    <customValue>
        <fullName>P2</fullName>
    </customValue>
    <customValue>
        <fullName>P3</fullName>
    </customValue>
    <customValue>
        <fullName>P4</fullName>
    </customValue>
    <customValue>
        <fullName>P5</fullName>
    </customValue>
    <customValue>
        <fullName>P6</fullName>
    </customValue>
    <customValue>
        <fullName>P7</fullName>
    </customValue>
    <customValue>
        <fullName>P8</fullName>
    </customValue>
    <customValue>
        <fullName>P9</fullName>
    </customValue>
    <customValue>
        <fullName>P10</fullName>
    </customValue>
    <customValue>
        <fullName>P11</fullName>
    </customValue>
    <customValue>
        <fullName>P12</fullName>
    </customValue>
    <masterLabel>Period</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/Services/FunnelAdditionTargetService.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class FunnelAdditionTargetService {
    private static FunnelAdditionTargetService m_actions;
    public static FunnelAdditionTargetService Action {
        get {
            if(m_actions != null) { return m_actions;}
            m_actions = new FunnelAdditionTargetService();
            return m_actions;
        }
    }

    public List<Funnel_Addition_Target__c> GenerateNewTargetForQuotaConfiguration(Annual_Quota_Config__c config) {
        List<Period> fyPeriods = DefaultPeriodSelector.Instance.GetByFiscalYear(config.Fiscal_Year__c);
        List<Funnel_Addition_Target__c> newTargets = new List<Funnel_Addition_Target__c>();
        if(!fyPeriods.isEmpty()) {
            for(Period p : fyPeriods) {
                Funnel_Addition_Target__c target = new Funnel_Addition_Target__c(
                        Quote_Config__c = config.Id,
                        Fiscal_Year__c = config.Fiscal_Year__c,
                        Rep__c = config.Rep__c,
                        Territory__c = config.Territory__c,
                        Period__c = String.valueOf('P' + p.Number)
                );
                newTargets.add(target);
            }
        }
        return newTargets;
    }

}