.idea/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chemical__c</fullName>
        <label>Chemical</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hydrogen Peroxide</fullName>
                </value>
                <value>
                    <fullName>Ferrous Chloride</fullName>
                </value>
                <value>
                    <fullName>Ferric Chloride</fullName>
                </value>
                <value>
                    <fullName>Ferric Sulfate</fullName>
                </value>
                <value>
                    <fullName>Sodium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>USP-OC31</fullName>
                </value>
                <value>
                    <fullName>Peracetic Acid</fullName>
                </value>
                <value>
                    <fullName>Sodium Bisulfite</fullName>
                </value>
                <value>
                    <fullName>Nitrate</fullName>
                </value>
                <value>
                    <fullName>Ferrous Sulfate</fullName>
                </value>
                <value>
                    <fullName>Sodium Persulfate</fullName>
                </value>
                <value>
                    <fullName>Klozur</fullName>
                </value>
                <value>
                    <fullName>Cloevis Precursor</fullName>
                </value>
                <value>
                    <fullName>Sulfelox</fullName>
                </value>
                <value>
                    <fullName>Chelated Fe</fullName>
                </value>
                <value>
                    <fullName>Calcium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>Sodium Hypochlorite</fullName>
                </value>
                <value>
                    <fullName>Permanganates Sodium</fullName>
                </value>
                <value>
                    <fullName>Permanganates Potassium</fullName>
                </value>
                <value>
                    <fullName>Magnesium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>Hydrochloric Acid</fullName>
                </value>
                <value>
                    <fullName>Sulfuric Acid</fullName>
                </value>
                <value>
                    <fullName>Nitric Acid</fullName>
                </value>
                <value>
                    <fullName>Citric Acid</fullName>
                </value>
                <value>
                    <fullName>Acetic Acid</fullName>
                </value>
                <value>
                    <fullName>Caustic Soda</fullName>
                </value>
                <value>
                    <fullName>Sodium Percarbonate</fullName>
                </value>
                <value>
                    <fullName>Specialty oxidants (USP-OC31E)</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Service/Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_PO_Start_Date__c</fullName>
        <label>Contract/PO Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Test Classes/opportunityPathControllerTest.cls
@IsTest
private class opportunityPathControllerTest {

    @IsTest
    public static void stage0Test() {
        Opportunity a = new Opportunity();
        a.Name = 'Test Opp ';
        a.StageName = '0 - Target';
        a.Amount = 20000;
        a.CloseDate = Date.today().addDays(10);
        a.Chemical__c = 'Hydrogen Peroxide';

        insert a;

        Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(a);
            opportunityPathController pathController = new opportunityPathController(sc);

            PageReference pageRef = Page.opportunityPath;
            pageRef.getParameters().put('id', String.valueOf(a.Id));
            Test.setCurrentPage(pageRef);
        Test.stopTest();
    }

    @IsTest
    public static void stage1est() {
        Opportunity a = new Opportunity();
        a.Name = 'Test Opp ';
        a.StageName = '1- Prospect';
        a.Amount = 20000;
        a.CloseDate = Date.today().addDays(10);
        a.Chemical__c = 'Hydrogen Peroxide';


        insert a;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        opportunityPathController pathController = new opportunityPathController(sc);

        PageReference pageRef = Page.opportunityPath;
        pageRef.getParameters().put('id', String.valueOf(a.Id));
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }

    @IsTest
    public static void stage2Test() {
        Opportunity a = new Opportunity();
        a.Name = 'Test Opp ';
        a.StageName = '2- Qualified';
        a.Amount = 20000;
        a.CloseDate = Date.today().addDays(10);
        a.Chemical__c = 'Hydrogen Peroxide';


        insert a;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        opportunityPathController pathController = new opportunityPathController(sc);

        PageReference pageRef = Page.opportunityPath;
        pageRef.getParameters().put('id', String.valueOf(a.Id));
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }

    @IsTest
    public static void stage3Test() {
        Opportunity a = new Opportunity();
        a.Name = 'Test Opp ';
        a.StageName = '3- Validated';
        a.Amount = 20000;
        a.CloseDate = Date.today().addDays(10);
        a.Chemical__c = 'Hydrogen Peroxide';


        insert a;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        opportunityPathController pathController = new opportunityPathController(sc);

        PageReference pageRef = Page.opportunityPath;
        pageRef.getParameters().put('id', String.valueOf(a.Id));
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }

    @IsTest
    public static void stage4Test() {
        Opportunity a = new Opportunity();
        a.Name = 'Test Opp ';
        a.StageName = '4- Proposal';
        a.Amount = 20000;
        a.CloseDate = Date.today().addDays(10);
        a.Chemical__c = 'Hydrogen Peroxide';


        insert a;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        opportunityPathController pathController = new opportunityPathController(sc);

        PageReference pageRef = Page.opportunityPath;
        pageRef.getParameters().put('id', String.valueOf(a.Id));
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }

    @IsTest
    public static void stage5Test() {
        Opportunity a = new Opportunity();
        a.Name = 'Test Opp ';
        a.StageName = '5 - Closed/Won ';
        a.Amount = 20000;
        a.CloseDate = Date.today().addDays(10);
        a.Contract_PO_Start_Date__c = Date.valueOf(TestDataFactory.endDateWithoutData);
        a.Chemical__c = 'Hydrogen Peroxide';


        insert a;

        Test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(a);
        opportunityPathController pathController = new opportunityPathController(sc);

        PageReference pageRef = Page.opportunityPath;
        pageRef.getParameters().put('id', String.valueOf(a.Id));
        Test.setCurrentPage(pageRef);
        Test.stopTest();
    }
}