.idea/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Chemical_Global__c</fullName>
        <label>Chemical</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Chemical</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chemical__c</fullName>
        <label>Chemical</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hydrogen Peroxide</fullName>
                </value>
                <value>
                    <fullName>Ferrous Chloride</fullName>
                </value>
                <value>
                    <fullName>Ferric Chloride</fullName>
                </value>
                <value>
                    <fullName>Ferric Sulfate</fullName>
                </value>
                <value>
                    <fullName>Sodium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>USP-OC31</fullName>
                </value>
                <value>
                    <fullName>Peracetic Acid</fullName>
                </value>
                <value>
                    <fullName>Sodium Bisulfite</fullName>
                </value>
                <value>
                    <fullName>Nitrate</fullName>
                </value>
                <value>
                    <fullName>Ferrous Sulfate</fullName>
                </value>
                <value>
                    <fullName>Sodium Persulfate</fullName>
                </value>
                <value>
                    <fullName>Klozur</fullName>
                </value>
                <value>
                    <fullName>Cloevis Precursor</fullName>
                </value>
                <value>
                    <fullName>Sulfelox</fullName>
                </value>
                <value>
                    <fullName>Chelated Fe</fullName>
                </value>
                <value>
                    <fullName>Calcium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>Sodium Hypochlorite</fullName>
                </value>
                <value>
                    <fullName>Permanganates Sodium</fullName>
                </value>
                <value>
                    <fullName>Permanganates Potassium</fullName>
                </value>
                <value>
                    <fullName>Magnesium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>Hydrochloric Acid</fullName>
                </value>
                <value>
                    <fullName>Sulfuric Acid</fullName>
                </value>
                <value>
                    <fullName>Nitric Acid</fullName>
                </value>
                <value>
                    <fullName>Citric Acid</fullName>
                </value>
                <value>
                    <fullName>Acetic Acid</fullName>
                </value>
                <value>
                    <fullName>Caustic Soda</fullName>
                </value>
                <value>
                    <fullName>Sodium Percarbonate</fullName>
                </value>
                <value>
                    <fullName>Specialty oxidants (USP-OC31E)</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Service/Consulting</fullName>
                </value>
                <value>
                    <fullName>OptiCal</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_PO_Start_Date__c</fullName>
        <label>Contract/PO Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

force-app/main/default/classes/Test Classes/AccuracyAndTargetTest.cls
@IsTest
private class AccuracyAndTargetTest {
    @IsTest
    static void regressionCoverage() {
        Test.startTest();
        TestDataFactory.init();
        User u = TestDataFactory.PrepareUsersAndRoles();

        Account a = new Account(Name = 'AnT Test Account'); insert a;

        List<Opportunity> opps = new List<Opportunity>();
        opps.add(new Opportunity(
                Name = 'AnT Test Opp 001', StageName = '4 - Proposal',
                Amount = 123400.00, CurrencyIsoCode = 'USD',
                CloseDate = Date.today(), AccountId = a.Id, OwnerId = u.Id, Probability = 70 , Chemical__c = 'Hydrogen Peroxide', Chemical_Global__c = 'OptiCal'
        ));
        opps.add(new Opportunity(
                Name = 'AnT Test Opp 002', StageName = '4 - Proposal',
                Amount = 123400.00, CurrencyIsoCode = 'USD',
                CloseDate = Date.today(), AccountId = a.Id, OwnerId = u.Id, Probability = 70 , Chemical__c = 'Hydrogen Peroxide', Chemical_Global__c = 'OptiCal'
        ));
        opps.add(new Opportunity(
                Name = 'AnT Test Opp 003', StageName = '4 - Proposal',
                Amount = 123400.00, CurrencyIsoCode = 'USD',
                CloseDate = Date.today(), AccountId = a.Id, OwnerId = u.Id, Probability = 70 , Chemical__c = 'Hydrogen Peroxide', Chemical_Global__c = 'OptiCal'
        ));
        opps.add(new Opportunity(
                Name = 'AnT Test Opp 004', StageName = '4 - Proposal',
                Amount = 2345600.00, CurrencyIsoCode = 'USD' ,
                CloseDate = Date.today(), AccountId = a.Id, OwnerId = u.Id, Probability = 70, Chemical__c = 'Hydrogen Peroxide', Chemical_Global__c = 'OptiCal'
        ));
        insert opps;

        System.runAs(u) {
            AccuracyAndTargetCalculator.Execute(
                    AccuracyAndTargetCalculator.Mode.StartOfPeriod,
                    AccuracyAndTargetCalculator.State.IgnoreCurrentDate
            );
            opps[2].StageName = '5 - Closed/Won';
            opps[2].Contract_PO_Start_Date__c = Date.today().addMonths(2);
            update opps[2];
            // shift to last day of month so that it runs EoM calculations
            AccuracyAndTargetCalculator.M_TODAY = Date.today().addMonths(1).toStartOfMonth().addDays(-1);
            AccuracyAndTargetCalculator.Execute(
                    AccuracyAndTargetCalculator.Mode.EndOfPeriod,
                    AccuracyAndTargetCalculator.State.IgnoreCurrentDate
            );
        }
        Test.stopTest();
    }
}