.idea/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Budget_Confirmed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Budget Confirmed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Budget_Range__c</fullName>
        <label>Budget Range</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>&lt;$50K</fullName>
                </value>
                <value>
                    <fullName>$50-100K</fullName>
                </value>
                <value>
                    <fullName>$100-$500K</fullName>
                </value>
                <value>
                    <fullName>&gt;$500K</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CERCOMPLETED__c</fullName>
        <defaultValue>false</defaultValue>
        <label>CER Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Chemical_Global__c</fullName>
        <label>Chemical</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Chemical</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Chemical__c</fullName>
        <label>Chemical</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hydrogen Peroxide</fullName>
                </value>
                <value>
                    <fullName>Ferrous Chloride</fullName>
                </value>
                <value>
                    <fullName>Ferric Chloride</fullName>
                </value>
                <value>
                    <fullName>Ferric Sulfate</fullName>
                </value>
                <value>
                    <fullName>Sodium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>USP-OC31</fullName>
                </value>
                <value>
                    <fullName>Peracetic Acid</fullName>
                </value>
                <value>
                    <fullName>Sodium Bisulfite</fullName>
                </value>
                <value>
                    <fullName>Nitrate</fullName>
                </value>
                <value>
                    <fullName>Ferrous Sulfate</fullName>
                </value>
                <value>
                    <fullName>Sodium Persulfate</fullName>
                </value>
                <value>
                    <fullName>Klozur</fullName>
                </value>
                <value>
                    <fullName>Cloevis Precursor</fullName>
                </value>
                <value>
                    <fullName>Sulfelox</fullName>
                </value>
                <value>
                    <fullName>Chelated Fe</fullName>
                </value>
                <value>
                    <fullName>Calcium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>Sodium Hypochlorite</fullName>
                </value>
                <value>
                    <fullName>Permanganates Sodium</fullName>
                </value>
                <value>
                    <fullName>Permanganates Potassium</fullName>
                </value>
                <value>
                    <fullName>Magnesium Hydroxide</fullName>
                </value>
                <value>
                    <fullName>Hydrochloric Acid</fullName>
                </value>
                <value>
                    <fullName>Sulfuric Acid</fullName>
                </value>
                <value>
                    <fullName>Nitric Acid</fullName>
                </value>
                <value>
                    <fullName>Citric Acid</fullName>
                </value>
                <value>
                    <fullName>Acetic Acid</fullName>
                </value>
                <value>
                    <fullName>Caustic Soda</fullName>
                </value>
                <value>
                    <fullName>Sodium Percarbonate</fullName>
                </value>
                <value>
                    <fullName>Specialty oxidants (USP-OC31E)</fullName>
                </value>
                <value>
                    <fullName>Equipment</fullName>
                </value>
                <value>
                    <fullName>Service/Consulting</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Contract_PO_Duration__c</fullName>
        <inlineHelpText>Months</inlineHelpText>
        <label>Contract/PO Duration</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contract_PO_End_Date__c</fullName>
        <label>Contract/PO End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_PO_Start_Date__c</fullName>
        <label>Contract/PO Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Current_Year_Revenue__c</fullName>
        <formula>IF(
AND(
YEAR( Contract_PO_Start_Date__c ) = YEAR(TODAY()),
YEAR( ADDMONTHS( Contract_PO_Start_Date__c ,  Contract_PO_Duration__c ) ) = YEAR(TODAY())
),
Amount ,
IF(
AND(
YEAR( Contract_PO_Start_Date__c ) &lt; YEAR(TODAY()),
YEAR( ADDMONTHS( Contract_PO_Start_Date__c , Contract_PO_Duration__c ) ) &gt; YEAR(TODAY())
),
12 * ( Amount / Contract_PO_Duration__c),
IF(
AND(
YEAR( Contract_PO_Start_Date__c ) = YEAR(TODAY()),
YEAR(ADDMONTHS( Contract_PO_Start_Date__c , Contract_PO_Duration__c )) &gt; YEAR(TODAY())
),
(12 - MONTH( Contract_PO_Start_Date__c )) * ( Amount / Contract_PO_Duration__c),
IF(
AND(
YEAR( Contract_PO_Start_Date__c ) &lt; YEAR(TODAY()),
YEAR(ADDMONTHS( Contract_PO_Start_Date__c , Contract_PO_Duration__c )) = YEAR(TODAY())
),
MONTH(ADDMONTHS( Contract_PO_Start_Date__c , Contract_PO_Duration__c )) * ( Amount / Contract_PO_Duration__c),
0))))</formula>
        <label>Current Year Revenue</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Drivers__c</fullName>
        <label>Drivers</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Environmental REgs</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Estimated_Monthly_Amount__c</fullName>
        <formula>Amount /  Contract_PO_Duration__c</formula>
        <label>Estimated Monthly Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Revenue_Year__c</fullName>
        <label>Estimated Revenue Year</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Territory</valueSetName>
        </valueSet>
    </fields>
</CustomObject>

force-app/main/default/classes/Selectors/OpportunitySelector.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class OpportunitySelector extends SObjectSelector {
    public OpportunitySelector(){
        super(Opportunity.SObjectType);
    }

    private static OpportunitySelector m_instance;
    public static OpportunitySelector Instance {
        get {
            if(m_instance != null) { return m_instance;}
            m_instance = new OpportunitySelector();
            return m_instance;
        }
    }

    public override Set<SObjectField> GetDefaultFields(){
        return new Set<SObjectField>{
                Opportunity.Id,
                Opportunity.Name,
                Opportunity.Amount,
                Opportunity.CloseDate,
                Opportunity.StageName,
                Opportunity.Type,
                Opportunity.Chemical__c,
                Opportunity.Chemical_Global__c,
                Opportunity.Territory__c,
                Opportunity.External_Id__c,
                Opportunity.Probability,
                Opportunity.Description,
                Opportunity.AccountId,
                Opportunity.Budget_Confirmed__c,
                Opportunity.Budget_Range__c,
                Opportunity.Comments__c,
                Opportunity.ContactId,
                Opportunity.IsClosed,
                Opportunity.Estimated_Monthly_Amount__c,
                Opportunity.Estimated_Revenue_Year__c,
                Opportunity.Current_Year_Revenue__c,
                Opportunity.Drivers__c,
                Opportunity.CERCOMPLETED__c,
                Opportunity.Contract_PO_Start_Date__c,
                Opportunity.Contract_PO_End_Date__c,
                Opportunity.Contract_PO_Duration__c
        };
    }

    public List<Opportunity> GetAll(){
        return queryAll();
    }

    public List<Opportunity> GetById(Set<Id> keyset) {
        return queryById(keyset);
    }

    public List<Opportunity> GetByTerritory(String key) {
        return GetQueryFactory().WithCriteria(Criteria.Equals(Opportunity.Territory__c, key)).Execute();
    }

    public List<Opportunity> GetByExternalId(Set<String> keyset){
        return GetQueryFactory().WithCriteria(Criteria.ValueIn(Opportunity.External_Id__c, keyset)).Execute();
    }

    public List<Opportunity> GetOne() {
        return querySome(1);
    }

}