.idea/src/objects/Order_Product__c.object
<CustomObject>
    <fields>
        <fullName>UniqueOrderProductID__c</fullName>
        <externalId>true</externalId>
        <label>Unique  Order Product ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Product</label>
    <nameField>
        <label>Order Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order Products</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Utils/ScheduledJobs/BulkDeleteOrderProducts.cls
/**
 * 
 * Class Description
 *
 * @author barne
 * @version 1.0.0
 */

public with sharing class BulkDeleteOrderProducts implements Database.Batchable<Sobject>, Schedulable{

    private String query;

    public BulkDeleteOrderProducts() {
        this.query = BulkDeleteUtil.Instance.GenerateQueryFor(Order_Product__c.SObjectType, Order_Product__c.UniqueOrderProductID__c);
    }

    public void execute(SchedulableContext param1) {
        Database.executeBatch(this);
    }

    public Database.QueryLocator start(Database.BatchableContext param1) {
        return Database.getQueryLocator(query);
    }
    public void execute(Database.BatchableContext param1, List<Sobject> param2) {
        BulkDeleteUtil.Instance.Execute(param2);
    }

    public void finish(Database.BatchableContext param1) {
    }


}